// Generated file - do not edit manually
// This file is auto-generated from Rust constants
// Run 'npm run generate-constants' to update

export const EVENTS = {
  AGENT_EVENT: 'agent-event',
  AGENT_PROCESSING_COMPLETE: 'agent-processing-complete',
  AGENT_PROCESSING_ERROR: 'agent-processing-error',
  AGENT_STATE_CHANGED: 'agent-state-changed',
  AGENT_TOOL_CALL: 'agent-tool-call',
  AGENT_THOUGHT_PROCESS: 'agent-thought-process',
  AGENT_STOPPING: 'agent-stopping',
  AGENT_STATUS_UPDATE: 'agent-status-update',
  AGENT_ACTIVE: 'agent-active',
  AGENT_ERROR: 'agent-error',
  AGENT_TRANSCRIPTION_START: 'agent-transcription-start',
  AGENT_TRANSCRIPTION_STOP: 'agent-transcription-stop',
  AGENT_CANCEL: 'agent-cancel',
  AGENT_COMMITTED: 'agent-committed',
  AGENT_FORCE_STOP: 'agent-force-stop',
  AGENT_FORCE_CLEANUP: 'agent-force-cleanup',
  STREAMING_TEXT_STREAM: 'agent-text-stream',
  STREAMING_STREAM_START: 'agent-stream-start',
  STREAMING_STREAM_END: 'agent-stream-end',
  DICTATION_STARTED: 'app-dictation-started',
  DICTATION_FINISHED: 'app-dictation-finished',
  DICTATION_PARTIAL_RESULT: 'app-dictation-partial-result',
  DICTATION_ERROR: 'app-dictation-error',
  DICTATION_STATE_CHANGED: 'dictation-state-changed',
  DICTATION_ACTIVE: 'dictation-active',
  DICTATION_CANCELLED: 'dictation-cancelled',
  DICTATION_TRANSCRIPTION_START: 'dictation-transcription-start',
  DICTATION_TRANSCRIPTION_STOP: 'dictation-transcription-stop',
  DICTATION_COMMITTED: 'dictation-committed',
  DICTATION_STOP: 'dictation-stop',
  DICTATION_TRANSCRIPTION_CANCEL: 'dictation-cancel',
  DICTATION_TRANSCRIPTION_FORCE_STOP: 'dictation-transcription-force-stop',
  DICTATION_TRANSCRIPTION_FORCE_CLEANUP: 'dictation-transcription-force-cleanup',
  DICTATION_STOPPED: 'app-dictation-stopped',
  VOICE_TRANSCRIPTION_FINAL_RESULT: 'voice-transcription:final-result',
  VOICE_TRANSCRIPTION_DICTATION_STOPPED: 'voice-transcription:dictation-stopped',
  VOICE_TRANSCRIPTION_ERROR: 'voice-transcription:error',
  VOICE_TRANSCRIPTION_DICTATION_STARTED: 'voice-transcription:dictation-started',
  VOICE_TRANSCRIPTION_PARTIAL_RESULT: 'voice-transcription:partial-result',
  TIMER_EXPIRED: 'timer-expired',
  TIMER_QUEUED: 'timer-queued',
  TIMER_PROCESSED: 'timer-processed',
  TIMER_STATUS_UPDATE: 'timer-status-update',
  FORCE_STOP_TRANSCRIPTION: 'force-stop-transcription',
  UI_BAR_STATE_CHANGED: 'bar-state-changed',
  UI_REQUEST_AUDIO_PLAYBACK_TEST: 'request-audio-playback-test',
  UI_KEY_PRESS_VISUALIZATION: 'key-press-visualization',
  UI_CLICK_VISUALIZATION: 'click-visualization',
  UI_UI_CURSOR_HIGHLIGHT_START: 'ui-cursor-highlight-start',
  UI_UI_CURSOR_HIGHLIGHT_MOVE: 'ui-cursor-highlight-move',
  UI_UI_CURSOR_HIGHLIGHT_STOP: 'ui-cursor-highlight-stop',
  MENU_SETTINGS_REQUESTED: 'settings-requested',
  MENU_DEVTOOLS_REQUESTED: 'devtools-requested',
  MENU_PERMISSIONS_REQUESTED: 'permissions-requested',
  MENU_FEEDBACK_REQUESTED: 'feedback-requested',
  MENU_HELP_REQUESTED: 'help-requested',
  MENU_NEW_CHAT_REQUESTED: 'new-chat-requested',
  MENU_IMPORT_CHAT_REQUESTED: 'import-chat-requested',
  MENU_EXPORT_CHAT_REQUESTED: 'export-chat-requested',
  MENU_TOGGLE_FLOATING_BAR_REQUESTED: 'toggle-floating-bar-requested',
  MENU_TOGGLE_DEV_PANEL_REQUESTED: 'toggle-dev-panel-requested',
  MENU_TOGGLE_FULLSCREEN_REQUESTED: 'toggle-fullscreen-requested',
  MENU_MINIMIZE_WINDOW_REQUESTED: 'minimize-window-requested',
  MENU_ZOOM_WINDOW_REQUESTED: 'zoom-window-requested',
  MENU_UPDATE_CHECK_REQUESTED: 'update-check-requested',
  MENU_ABOUT_REQUESTED: 'about-requested',
  MENU_EDIT_UNDO: 'menu-edit-undo',
  MENU_EDIT_REDO: 'menu-edit-redo',
  MENU_EDIT_CUT: 'menu-edit-cut',
  MENU_EDIT_COPY: 'menu-edit-copy',
  MENU_EDIT_PASTE: 'menu-edit-paste',
  MENU_EDIT_SELECT_ALL: 'menu-edit-select-all',
  TTS_AUDIO_READY: 'tts-audio-ready',
  TTS_STOP_REQUESTED: 'tts-stop-requested',
  ALWAYS_LISTENING_MODE_CHANGED: 'always-listening-mode-changed',
  ALWAYS_LISTENING_WAKE_WORD_DETECTED: 'always-listening:wake-word-detected',
  ALWAYS_LISTENING_TOGGLE_DICTATION_REQUEST: 'toggle-dictation-request',
  ALWAYS_LISTENING_STARTED: 'always-listening:started',
  ALWAYS_LISTENING_STOPPED: 'always-listening:stopped',
  ALWAYS_LISTENING_ACTIVATED: 'always-listening:activated',
  ALWAYS_LISTENING_DEACTIVATED: 'always-listening:deactivated',
  ALWAYS_LISTENING_STOP_REQUESTED: 'always-listening:stop-requested',
  ALWAYS_LISTENING_TRANSCRIPTION: 'always-listening:transcription',
  ALWAYS_LISTENING_COMMAND_PROCESSED: 'always-listening:command-processed',
  ALWAYS_LISTENING_EVENT: 'always-listening-event',
  ALWAYS_LISTENING_STOPPED_BY_COMMAND: 'always-listening:stopped-by-command',
  ALWAYS_LISTENING_RETURN_TO_WAKE_WORD: 'always-listening:return-to-wake-word',
  PERMISSIONS_CHANGED: 'permissions-changed',
  PERMISSIONS_RESTART_REQUIRED: 'permissions-restart-required',
  PERMISSIONS_GUIDANCE_NEEDED: 'permission-guidance-needed',
  DEV_TOOL_NOTIFICATION: 'dev-tool-notification',
  MESSAGES_USER_MESSAGE_SUBMITTED: 'user-message-submitted',
  CLOUD_WEBSOCKET_CONNECT: 'websocket-connect',
  CLOUD_WEBSOCKET_SEND: 'websocket-send',
  CLOUD_WEBSOCKET_DISCONNECT: 'websocket-disconnect',
  CLOUD_CONNECTOR_STATE: 'cloud-connector-state',
  CLOUD_CONNECTION_STATE: 'cloud-connection-state',
  CLOUD_COMMAND_RECEIVED: 'cloud-command-received',
  SYSTEM_ERROR_OCCURRED: 'error-occurred',
  SYSTEM_MCP_STATE_UPDATED: 'mcp_state_updated',
  SYSTEM_MOUSE_ENTERED_WINDOW: 'mouse-entered-window',
  SYSTEM_MOUSE_LEFT_WINDOW: 'mouse-left-window',
  ONBOARDING_COMPLETE: 'onboarding-complete',
  ONBOARDING_SKIPPED: 'onboarding-skipped',
  NOTIFICATIONS_TOAST: 'toast-notification',
  BAR_STATE_UPDATE: 'bar-state-update',
  BAR_COMPLETE_TRANSITION: 'floating-bar-complete-transition',
  BAR_CLEAR_ERROR: 'floating-bar-clear-error',
  BAR_CONFIG_CHANGED: 'floating-bar-config-changed',
  TOOLS_USAGE: 'tool-usage',
  TOOLS_APPROVAL_REQUEST: 'tool-approval-request',
  TOOLS_COMMAND_EXECUTION_START: 'command-execution-start',
  TOOLS_COMMAND_EXECUTION_END: 'command-execution-end',
  CONTINUATION_AGENT_REQUEST: 'agent-continuation-request',
  CONTINUATION_AGENT_RESPONSE: 'agent-continuation-response',
  DICTATION_STATE_FORCE_RESET: 'dictation-state-force-reset',
  DICTATION_STATE_INPUT_CHANGED: 'dictation-input-state-changed',
  SHORTCUTS_AGENT_MODE: 'shortcut-agent-mode',
  SHORTCUTS_DICTATION_INPUT: 'shortcut-dictation-input',
  TOOL_CHOICE_CONFIG_CHANGED: 'tool-choice-config-changed',
  TOOL_CHOICE_CONFIG_RESET: 'tool-choice-config-reset',
  TOOL_CHOICE_ENABLED_CHANGED: 'tool-choice-enabled-changed',
  PLUGIN_VOICE_TRANSCRIPTION_DICTATION_STARTED: 'plugin:voice-transcription:dictation-started',
  PLUGIN_VOICE_TRANSCRIPTION_DICTATION_STOPPED: 'plugin:voice-transcription:dictation-stopped',
  PLUGIN_ALWAYS_LISTENING_STARTED: 'plugin:always-listening:started',
  PLUGIN_ALWAYS_LISTENING_STOPPED: 'plugin:always-listening:stopped',
} as const;

export const TIMEOUTS = {
  MICRO_DELAY_MS: 10,
  MINIMAL_DELAY_MS: 20,
  SMALL_DELAY_MS: 50,
  SHORT_DELAY_MS: 100,
  MEDIUM_DELAY_MS: 150,
  ANIMATION_DELAY_MS: 300,
  STANDARD_DELAY_MS: 500,
  LONG_DELAY_MS: 800,
  VERY_LONG_DELAY_MS: 1000,
  EXTENDED_DELAY_MS: 2000,
  MAX_DELAY_MS: 3000,
  SOUND_DEBOUNCE_MS: 300,
  HEARTBEAT_INTERVAL_MS: 30000,
  CLOUD_CONNECTION_TIMEOUT_MS: 10000,
  CLOUD_RECONNECT_DELAY_MS: 5000,
  ANIMATION_FAST_MS: 150,
  ANIMATION_NORMAL_MS: 300,
  ANIMATION_SLOW_MS: 500,
  STANDARD_TIMEOUT_SECONDS: 10,
  BROWSER_TIMEOUT_SECONDS: 30,
  NETWORK_TIMEOUT_SECONDS: 30,
  HEARTBEAT_INTERVAL_SECONDS: 30,
  STATUS_UPDATE_INTERVAL_SECONDS: 30,
  HTTP_CONNECT_TIMEOUT_SECONDS: 10,
  HTTP_REQUEST_TIMEOUT_SECONDS: 120,
  ERROR_RECOVERY_MAX_RETRY_DELAY_SECONDS: 10,
  ERROR_RECOVERY_TIMEOUT_THRESHOLD_SECONDS: 30,
  ERROR_RECOVERY_WAIT_SHORT_SECONDS: 3,
  ERROR_RECOVERY_WAIT_LONG_SECONDS: 10,
  TESTING_HUMAN_AVERAGE_SECONDS: 480,
  TESTING_AGENT_AVERAGE_SECONDS: 120,
  TESTING_RESPONSE_TIME_LIMIT_SECONDS: 30,
  TESTING_QA_TIMEOUT_SECONDS: 60,
  VOICE_CACHE_VALIDITY_SECONDS: 30,
  VOICE_STATE_CHECK_SECONDS: 2,
  VOICE_WAKE_DETECTION_SECONDS: 60,
  CLOUD_HEARTBEAT_INTERVAL_SECONDS: 30,
  CLOUD_STATUS_INTERVAL_SECONDS: 30,
  CLOUD_WATCHDOG_INTERVAL_SECONDS: 60,
  CLOUD_MAX_RETRY_DELAY_SECONDS: 300,
  MCP_OPERATION_TIMEOUT_SECONDS: 5,
  MCP_GRACEFUL_SHUTDOWN_SECONDS: 3,
  MCP_MAX_BACKOFF_DELAY_SECONDS: 30,
  MCP_SERVER_STARTUP_TIMEOUT_SECONDS: 45,
  ORCHESTRATOR_PARALLEL_EXECUTION_TIMEOUT_SECONDS: 5,
  ORCHESTRATOR_MIN_TIMEOUT_SECONDS: 30,
  ORCHESTRATOR_MAX_TIMEOUT_SECONDS: 600,
  AGENT_STEP_DELAY_SECONDS: 1,
  BROWSER_CONNECTION_TIMEOUT_SECONDS: 8,
  BROWSER_PAGE_OPERATION_TIMEOUT_SECONDS: 2,
  BROWSER_CLICK_TIMEOUT_SECONDS: 1,
  DESKTOP_TYPING_TIMEOUT_SECONDS: 30,
  VISUAL_PROCESSING_TIMEOUT_SECONDS: 10,
  VISUAL_TEMPORAL_CONTEXT_SECONDS: 30,
  COLLABORATIVE_AI_KNOWLEDGE_RETRIEVAL_SECONDS: 30,
  COLLABORATIVE_AI_COORDINATION_SECONDS: 60,
  STANDARD_TIMEOUT_MS: 10000,
  BROWSER_TIMEOUT_MS: 30000,
  DICTATION_MONITOR_INTERVAL_MS: 50,
  AGENT_MONITOR_INTERVAL_MS: 100,
  TREE_SEARCH_INTERVAL_MS: 250,
  MOUSE_MICRO_DELAY_MS: 10,
  MOUSE_CLICK_DELAY_MS: 50,
  MOUSE_ACTION_DELAY_MS: 100,
  MOUSE_SEQUENCE_DELAY_MS: 300,
  DOUBLE_CLICK_DELAY_MS: 500,
  UI_FADE_DELAY_MS: 300,
  UI_SLIDE_DELAY_MS: 600,
  UI_NOTIFICATION_DISPLAY_MS: 3000,
  PERMISSION_CHECK_DELAY_MS: 1000,
  SCREEN_RECORDING_CHECK_DELAY_MS: 2000,
  SYSTEM_SETTINGS_OPERATION_TIMEOUT_MS: 3000,
  SYSTEM_SETTINGS_CHECK_TIMEOUT_MS: 5000,
  MCP_SERVER_STARTUP_DELAY_MS: 500,
  MCP_SERVER_RESTART_DELAY_MS: 1000,
  CLOUD_RETRY_BASE_DELAY_MS: 2000,
  CLOUD_HEARTBEAT_INTERVAL_MS: 30000,
  CLOUD_STATUS_INTERVAL_MS: 30000,
  TTS_PROCESSING_DELAY_MS: 1000,
  PARTIAL_BUFFER_DURATION_MS: 1500,
  FINAL_BUFFER_DURATION_MS: 5000,
  MIN_AUDIO_LENGTH_MS: 500,
  DEFAULT_NAVIGATION_TIMEOUT_MS: 30000,
  REPLICATE_TIMEOUT_SECONDS: 300,
  PERMISSION_CHECK_TIMEOUT_MS: 3000,
  AUDIO_DEVICE_DETECTION_TIMEOUT_MS: 3000,
  TOOL_EXECUTION_TIMEOUT_MS: 10000,
  MCP_INTEGRATION_TIMEOUT_MS: 30000,
  BROWSER_PAGE_LOAD_DELAY_MS: 1000,
  SHELL_COMMAND_DELAY_MS: 10,
} as const;

export const PORTS = {
  VITE_DEV_PORT: 1420,
  VITE_HMR_PORT: 1421,
  MCP_SERVER_PORT: 8080,
  WEBSOCKET_TEST_PORT: 8080,
  CHROME_DEBUG_PORT_PRIMARY: 9222,
  CHROME_DEBUG_PORT_ALT1: 9223,
  CHROME_DEBUG_PORT_ALT2: 9224,
} as const;

export const API_ENDPOINTS = {
  ENDPOINTS_ANTHROPIC_API_URL: 'https://api.anthropic.com/v1/messages',
  ENDPOINTS_OPENAI_API_URL: 'https://api.openai.com/v1/chat/completions',
  ENDPOINTS_GEMINI_API_BASE: 'https://generativelanguage.googleapis.com/v1beta/models',
  ENDPOINTS_CLOUD_SERVER_URL: 'wss://juno-cloud-backend.fly.dev/ws',
  ENDPOINTS_GITHUB_URL: 'https://github.com/juno-ai',
  ENDPOINTS_LOCALHOST_BASE: 'http://localhost',
  ENDPOINTS_LOCALHOST_CHROME_DEBUG: 'http://localhost:9222',
  ENDPOINTS_LOCALHOST_MCP_SERVER: 'http://localhost:8080',
  ENDPOINTS_WEBSOCKET_LOCALHOST: 'ws://localhost:8080',
  ENDPOINTS_ELEVENLABS_TTS_BASE: 'https://api.elevenlabs.io/v1/text-to-speech',
  ENDPOINTS_REPLICATE_API_BASE: 'https://api.replicate.com',
  ENDPOINTS_JUNO_CLOUD_WEBSOCKET: 'wss://juno-cloud-backend.fly.dev/ws',
  ENDPOINTS_DEV_SERVER_BASE: 'http://localhost:1420',
  ENDPOINTS_HMR_WEBSOCKET: 'ws://localhost:1421',
  COMPUTER_USE_API_TYPES_COMPUTER_20241022: 'computer_20241022',
  COMPUTER_USE_API_TYPES_COMPUTER_20250124: 'computer_20250124',
  COMPUTER_USE_API_TYPES_EDIT_TOOL_20250124: 'str_replace_based_edit_tool_20250124',
  COMPUTER_USE_API_TYPES_EDIT_TOOL_20250429: 'str_replace_based_edit_tool_20250429',
  COMPUTER_USE_API_TYPES_BASH_20250124: 'bash_20250124',
  BETA_FLAGS_COMPUTER_USE_2024_10_22: 'computer-use-2024-10-22',
  BETA_FLAGS_COMPUTER_USE_2025_01_24: 'computer-use-2025-01-24',
  BETA_FLAGS_PROMPT_CACHING: 'prompt-caching-2024-07-31',
  HTTP_HEADERS_CONTENT_TYPE: 'Content-Type',
  HTTP_HEADERS_X_API_KEY: 'x-api-key',
  HTTP_HEADERS_APPLICATION_JSON: 'application/json',
  HTTP_HEADERS_AUTHORIZATION: 'Authorization',
  HTTP_HEADERS_USER_AGENT: 'User-Agent',
  HTTP_HEADERS_ANTHROPIC_BETA: 'anthropic-beta',
  ANTHROPIC_CONTENT_TYPES_MESSAGE_START: 'message_start',
  ANTHROPIC_CONTENT_TYPES_CONTENT_BLOCK_START: 'content_block_start',
  ANTHROPIC_CONTENT_TYPES_CONTENT_BLOCK_DELTA: 'content_block_delta',
  ANTHROPIC_CONTENT_TYPES_CONTENT_BLOCK_STOP: 'content_block_stop',
  ANTHROPIC_CONTENT_TYPES_TEXT_DELTA: 'text_delta',
  ANTHROPIC_CONTENT_TYPES_INPUT_JSON_DELTA: 'input_json_delta',
  ANTHROPIC_CONTENT_TYPES_TOOL_USE: 'tool_use',
  ANTHROPIC_CONTENT_TYPES_TOOL_RESULT: 'tool_result',
  ANTHROPIC_CONTENT_TYPES_TEXT: 'text',
  PROVIDER_NAMES_ANTHROPIC: 'anthropic',
  PROVIDER_NAMES_OPENAI: 'openai',
  PROVIDER_NAMES_GEMINI: 'gemini',
  PROVIDER_NAMES_ELEVENLABS: 'elevenlabs',
  PROVIDER_NAMES_REPLICATE: 'replicate',
  PROVIDER_NAMES_SYSTEM: 'system',
  CLOUD_NETWORKING_MAX_CONNECTION_RETRIES: 10,
  CLOUD_NETWORKING_BASE_RETRY_DELAY_MS: 2000,
  CLOUD_NETWORKING_BACKOFF_MULTIPLIER: 2,
  CLOUD_NETWORKING_MAX_BACKOFF_EXPONENT: 5,
  CLOUD_NETWORKING_CONNECTION_CHECK_INTERVAL_MS: 5000,
  CLOUD_NETWORKING_WATCHDOG_TIMEOUT_MS: 60000,
  CLOUD_NETWORKING_MAX_RETRY_INTERVAL_MS: 300000,
  CLOUD_NETWORKING_HEARTBEAT_SEND_INTERVAL_MS: 30000,
  CLOUD_NETWORKING_STATUS_CHECK_INTERVAL_MS: 30000,
  CLOUD_NETWORKING_RECONNECTION_DELAY_MS: 5000,
} as const;

export const APP_IDENTITY = {
  APP_NAME: 'Juno',
  BUNDLE_IDENTIFIER: 'com.juno.app',
  PRODUCT_NAME: 'Juno',
  ENTITLEMENTS_FILE: 'juno.entitlements',
  CONFIG_DIR_NAME: '.juno',
  SCREENSHOT_PREFIX: 'juno_screenshot_',
  DEVICE_NAME_PREFIX: 'Juno-',
  CLOUD_WS_GLOBAL_VAR: '__JUNO_CLOUD_WS',
} as const;

export const UI = {
  WINDOW_LABELS_MAIN: 'main',
  WINDOW_LABELS_FLOATING_BAR: 'floating-bar',
  WINDOW_LABELS_FLOATING_PANEL: 'floating-panel',
  WINDOW_LABELS_ONBOARDING: 'onboarding',
  WINDOW_LABELS_SETTINGS: 'settings',
  TEXT_DISPLAY_MAX_KEYPRESS_VISUALIZATION_TEXT_LENGTH: 30,
  TEXT_DISPLAY_MAX_UI_PREVIEW_TEXT_LENGTH: 50,
  MOBILE_BREAKPOINT: 768,
  PERCENTAGE_MULTIPLIER: 100,
  SCROLL_WHEEL_EVENT_LINE_SCROLL: 120,
  DOUBLE_CLICK_INTERVAL_MS: 50,
  MAX_TREE_SEARCH_DEPTH: 100,
} as const;

export const AUDIO = {
  PROCESSING_SINC_LENGTH: 256,
  PROCESSING_OVERSAMPLING_FACTOR: 256,
  PROCESSING_AUDIO_RECV_TIMEOUT_MS: 100,
  WHISPER_SAMPLE_RATE: 16000,
  SOUND_DEBOUNCE_MS: 300,
  DEFAULT_SENSITIVITY: 0.5,
  AUDIO_RECV_TIMEOUT_MS: 100,
  DEFAULT_WAKE_WORDS: ['hey juno', 'computer'],
} as const;

export const COMMANDS = {
  SETTINGS_GET_ALL_SETTINGS: 'get_all_settings',
  SETTINGS_SAVE_ALL_SETTINGS: 'save_all_settings',
  SETTINGS_RESET_SETTINGS: 'reset_centralized_settings',
  SETTINGS_EXPORT_SETTINGS: 'export_settings',
  SETTINGS_IMPORT_SETTINGS: 'import_settings',
  SETTINGS_GET_KEYBOARD_SHORTCUTS: 'get_centralized_keyboard_shortcuts',
  SETTINGS_SET_KEYBOARD_SHORTCUTS: 'set_centralized_keyboard_shortcuts',
  SETTINGS_GET_FLOATING_BAR_SETTINGS: 'get_floating_bar_settings',
  SETTINGS_SET_FLOATING_BAR_SETTINGS: 'set_floating_bar_settings',
  SETTINGS_GET_AGENT_SETTINGS: 'get_agent_settings',
  SETTINGS_SET_AGENT_SETTINGS: 'set_agent_settings',
  SETTINGS_GET_PROVIDER_SETTINGS: 'get_centralized_provider_settings',
  SETTINGS_SET_PROVIDER_SETTINGS: 'set_centralized_provider_settings',
  SETTINGS_GET_CLOUD_SETTINGS: 'get_cloud_settings',
  SETTINGS_SET_CLOUD_SETTINGS: 'set_cloud_settings',
  SETTINGS_GET_AUDIO_SETTINGS: 'get_audio_settings',
  SETTINGS_SET_AUDIO_SETTINGS: 'set_audio_settings',
  SETTINGS_GET_TOOL_SETTINGS: 'get_tool_settings',
  SETTINGS_SET_TOOL_SETTINGS: 'set_tool_settings',
  SETTINGS_GET_ONBOARDING_SETTINGS: 'get_onboarding_settings',
  SETTINGS_SET_ONBOARDING_SETTINGS: 'set_onboarding_settings',
  SETTINGS_SET_AUTOSTART_ENABLED: 'set_autostart_enabled',
  CORE_GET_DEBUG_MODE: 'get_debug_mode',
  CORE_SET_DEBUG_MODE: 'set_debug_mode',
  CORE_GET_PERFORMANCE_MONITORING: 'get_performance_monitoring',
  CORE_SET_PERFORMANCE_MONITORING: 'set_performance_monitoring',
  CORE_CANCEL_AGENT_EXECUTION: 'cancel_agent_execution',
  CORE_GET_AGENT_EXECUTION_PROGRESS: 'get_agent_execution_progress',
  CORE_SET_AGENT_EXECUTION_PROGRESS: 'set_agent_execution_progress',
  CORE_GET_SYSTEM_CONTEXT: 'get_system_context',
  AGENT_SUBMIT_QUERY: 'submit_query',
  AGENT_GET_AGENT_MODE: 'get_agent_mode',
  AGENT_SET_AGENT_MODE: 'set_agent_mode',
  AGENT_GET_AGENT_TRIGGER_MODE: 'get_agent_trigger_mode',
  AGENT_SET_AGENT_TRIGGER_MODE: 'set_agent_trigger_mode',
  PROVIDERS_GET_PROVIDERS: 'get_providers',
  PROVIDERS_GET_ACTIVE_PROVIDER: 'get_active_provider',
  PROVIDERS_SET_ACTIVE_PROVIDER: 'set_active_provider',
  PROVIDERS_VALIDATE_PROVIDER_MODEL: 'validate_provider_model',
  PROVIDERS_GET_PROVIDER_MODELS: 'get_provider_models',
  PROVIDERS_UPDATE_PROVIDER_API_KEY: 'update_provider_api_key',
  PROVIDERS_UPDATE_PROVIDER_MODEL: 'update_provider_model',
  PROVIDERS_UPDATE_PROVIDER_MAX_TOKENS: 'update_provider_max_tokens',
  PROVIDERS_UPDATE_PROVIDER_TEMPERATURE: 'update_provider_temperature',
  PROVIDERS_UPDATE_PROVIDER_SYSTEM_PROMPT: 'update_provider_system_prompt',
  ALWAYS_LISTENING_START_ALWAYS_LISTENING: 'start_always_listening_mode',
  ALWAYS_LISTENING_STOP_ALWAYS_LISTENING: 'stop_always_listening_mode',
  ALWAYS_LISTENING_GET_ALWAYS_LISTENING_STATUS: 'get_always_listening_status',
  ALWAYS_LISTENING_SET_ALWAYS_LISTENING_SENSITIVITY: 'set_always_listening_sensitivity',
  ALWAYS_LISTENING_GET_ALWAYS_LISTENING_SENSITIVITY: 'get_always_listening_sensitivity',
  ALWAYS_LISTENING_SET_ALWAYS_LISTENING_WAKE_WORDS: 'set_always_listening_wake_words',
  ALWAYS_LISTENING_GET_ALWAYS_LISTENING_WAKE_WORDS: 'get_always_listening_wake_words',
  TTS_INVOKE_TTS: 'invoke_tts',
  TTS_SET_TTS_PROVIDER: 'set_tts_provider_command',
  TTS_GET_TTS_PROVIDER: 'get_tts_provider_command',
  TTS_STOP_TTS: 'stop_tts',
  DICTATION_GET_DICTATION_TRIGGER_MODE: 'get_dictation_trigger_mode',
  DICTATION_SET_DICTATION_TRIGGER_MODE: 'set_dictation_trigger_mode',
  DICTATION_GET_DICTATION_CLIPBOARD_ENABLED: 'get_dictation_clipboard_enabled',
  DICTATION_SET_DICTATION_CLIPBOARD_ENABLED: 'set_dictation_clipboard_enabled',
  DICTATION_FORCE_RESET_DICTATION_STATE: 'force_reset_dictation_state',
  DICTATION_GET_DICTATION_COMPREHENSIVE_STATUS: 'get_dictation_comprehensive_status',
  DICTATION_UPDATE_DICTATION_COMPONENT_STATE: 'update_dictation_component_state',
  DICTATION_TRANSITION_DICTATION_STATE: 'transition_dictation_state',
  PERMISSIONS_CHECK_PERMISSIONS_STATUS: 'check_permissions_status_native',
  PERMISSIONS_REQUEST_ACCESSIBILITY_PERMISSION: 'request_accessibility_permission_native',
  PERMISSIONS_REQUEST_MICROPHONE_PERMISSION: 'request_microphone_permission_native',
  PERMISSIONS_REQUEST_SCREEN_RECORDING_PERMISSION: 'request_screen_recording_permission_native',
  PERMISSIONS_REQUEST_INPUT_MONITORING_PERMISSION: 'request_input_monitoring_permission_native',
  PERMISSIONS_TEST_MICROPHONE_FUNCTIONALITY: 'test_microphone_functionality',
  UTILS_WAIT: 'wait',
  UTILS_GET_CLIPBOARD: 'get_clipboard',
  UTILS_SET_CLIPBOARD: 'set_clipboard',
  UTILS_LIST_APPS: 'list_apps',
  UTILS_CHECK_SERVER_STATUS: 'check_server_status',
  SCREENSHOTS_CAPTURE_SCREENSHOT: 'capture_screenshot_command',
  SCREENSHOTS_CAPTURE_ELEMENT_SCREENSHOT: 'capture_element_screenshot_command',
  SCREENSHOTS_CAPTURE_WINDOW_SCREENSHOT: 'capture_window_screenshot_command',
  SCREENSHOTS_CAPTURE_FOCUSED_WINDOW_SCREENSHOT: 'capture_focused_window_screenshot_command',
  CLOUD_START_PRODUCTION_CLOUD_CONNECTOR: 'start_production_cloud_connector',
  CLOUD_STOP_PRODUCTION_CLOUD_CONNECTOR: 'stop_production_cloud_connector',
  CLOUD_GET_PRODUCTION_CLOUD_STATUS: 'get_production_cloud_status',
  CLOUD_GET_CLOUD_CONFIG_STATUS: 'get_cloud_config_status',
  CLOUD_TEST_CLOUD_BACKEND_CONNECTION: 'test_cloud_backend_connection',
  CLOUD_ENABLE_CLOUD_BACKEND: 'enable_cloud_backend',
  CLOUD_DISABLE_CLOUD_BACKEND: 'disable_cloud_backend',
  CLOUD_TEST_WEBSOCKET_CONNECTION: 'test_websocket_connection',
  CLOUD_SEND_TEST_CLOUD_COMMAND: 'send_test_cloud_command',
  CLOUD_SIMULATE_CLOUD_COMMAND: 'simulate_cloud_command',
  CLOUD_GET_WEBSOCKET_DIAGNOSTICS: 'get_websocket_diagnostics',
  CLOUD_RUN_WEBSOCKET_TEST_SUITE: 'run_websocket_test_suite',
  CLOUD_HANDLE_CLOUD_MESSAGE: 'handle_cloud_message',
  CLOUD_EXECUTE_REMOTE_COMMAND: 'execute_remote_command',
  CLOUD_GET_CLOUD_CONNECTION_DIAGNOSTICS: 'get_cloud_connection_diagnostics',
} as const;

export const MEMORY = {
  LIMITS_DEFAULT_MAX_MESSAGES: 15,
  LIMITS_DEFAULT_MAX_TOKENS: 100000,
  LIMITS_DEFAULT_MIN_MESSAGES_TO_KEEP: 3,
  LIMITS_DEFAULT_SUMMARIZATION_BATCH_SIZE: 25,
  LIMITS_EMERGENCY_TOKEN_THRESHOLD: 180000,
  LIMITS_CRITICAL_SINGLE_MESSAGE_TOKENS: 50000,
  LIMITS_LARGE_MESSAGE_WARNING_TOKENS: 50000,
  LIMITS_MAX_SUMMARIES_TO_KEEP: 20,
  LIMITS_HOT_CONTEXT_SIZE: 10,
  LIMITS_EMERGENCY_MIN_KEEP: 2,
  TOKENS_CHARS_PER_TOKEN_TEXT: 4,
  TOKENS_CHARS_PER_TOKEN_BASE64_IMAGE: 15,
  TOKENS_CHARS_PER_TOKEN_TOOL_INPUT_IMAGE: 20,
  TOKENS_BASE_TOOL_CALL_TOKENS: 50,
  TOKENS_EMERGENCY_THRESHOLD_MULTIPLIER: 1.2,
  VISUAL_DEFAULT_SCREENSHOT_RETENTION_SECONDS: 300,
  VISUAL_DEFAULT_MAX_BASE64_SCREENSHOTS: 1,
  VISUAL_MIN_BASE64_CONTENT_LENGTH: 1000,
  VISUAL_MIN_SCREENSHOT_CONTENT_LENGTH: 10000,
  VISUAL_BASE64_CHAR_THRESHOLD_PERCENT: 80,
  SUMMARY_MAX_SHORT_CONTENT_LENGTH: 100,
  SUMMARY_MIN_KEYWORD_LENGTH: 3,
  SUMMARY_MAX_KEYWORDS_TO_EXTRACT: 5,
  SUMMARY_CONVERSATION_START_OFFSET_SECONDS: 3600,
  SUMMARY_SHORT_CONVERSATION_MAX_MESSAGES: 3,
  PERFORMANCE_MAX_CACHE_SIZE: 100,
  PERFORMANCE_DEFAULT_OPERATION_TIMEOUT_MS: 5000,
  PERFORMANCE_MEMORY_OPTIMIZATION_INTERVAL_MS: 300000,
  PERFORMANCE_MAX_LATEST_SUMMARIES_RETURNED: 5,
  PATTERNS_PNG_DATA_URL_PREFIX: 'data:image/png;base64,',
  PATTERNS_JPEG_DATA_URL_PREFIX: 'data:image/jpeg;base64,',
  PATTERNS_WEBP_DATA_URL_PREFIX: 'data:image/webp;base64,',
  PATTERNS_GENERIC_IMAGE_DATA_PREFIX: 'data:image/',
  PATTERNS_BASE64_IDENTIFIER: 'base64,',
} as const;

export const FILE_EXTENSIONS = {
  EXTENSIONS_JSON_EXT: '.json',
  EXTENSIONS_JSON: '.json',
  EXTENSIONS_RUST_EXT: '.rs',
  EXTENSIONS_RUST: '.rs',
  EXTENSIONS_TYPESCRIPT_EXT: '.ts',
  EXTENSIONS_TYPESCRIPT: '.ts',
  EXTENSIONS_JAVASCRIPT_EXT: '.js',
  EXTENSIONS_JAVASCRIPT: '.js',
  EXTENSIONS_MARKDOWN_EXT: '.md',
  EXTENSIONS_MARKDOWN: '.md',
  EXTENSIONS_LOG_EXTENSION: '.log',
  EXTENSIONS_LOG: '.log',
  EXTENSIONS_TMP_EXTENSION: '.tmp',
  EXTENSIONS_TMP: '.tmp',
  EXTENSIONS_CACHE_EXTENSION: '.cache',
  EXTENSIONS_CACHE: '.cache',
  EXTENSIONS_BACKUP_EXTENSION: '.backup',
  EXTENSIONS_BACKUP: '.backup',
  EXTENSIONS_TEXT_EXT: '.txt',
  EXTENSIONS_TEXT: '.txt',
  EXTENSIONS_CSV_EXT: '.csv',
  EXTENSIONS_CSV: '.csv',
} as const;

export const PERMISSION_TYPES = {
  ACCESSIBILITY: 'accessibility',
  SCREEN_RECORDING: 'screen_recording',
  MICROPHONE: 'microphone',
  INPUT_MONITORING: 'input_monitoring',
} as const;

export const CHROME_DEBUG = {
  PRIMARY: 9222,
  ALT1: 9223,
  ALT2: 9224,
} as const;

export const WINDOW_LABELS = {
  MAIN: 'main',
  FLOATING_BAR: 'floating-bar',
  FLOATING_PANEL: 'floating-panel',
  ONBOARDING: 'onboarding',
  SETTINGS: 'settings',
} as const;

// Frontend-specific constants (not duplicated from Rust)
export const CSS_CLASSES = {
  HIDDEN: 'hidden',
  VISIBLE: 'visible',
  LOADING: 'loading',
  ERROR: 'error',
  SUCCESS: 'success',
  FADE_IN: 'fade-in',
  FADE_OUT: 'fade-out',
  SLIDE_IN: 'slide-in',
  SLIDE_OUT: 'slide-out',
} as const;

export const LOCAL_STORAGE_KEYS = {
  USER_PREFERENCES: 'juno_user_preferences',
  CHAT_HISTORY: 'juno_chat_history',
  CLOUD_CONFIG: 'juno_cloud_config',
  VOICE_SETTINGS: 'juno_voice_settings',
  THEME_PREFERENCE: 'juno_theme',
  WINDOW_STATE: 'juno_window_state',
} as const;

export const REGEX_PATTERNS = {
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  URL: /^https?:\/\/.+/,
  JSON: /^[\s]*[{\[]/,
  WHITESPACE_ONLY: /^\s*$/,
  WAKE_WORD: /^[a-zA-Z\s]{2,20}$/,
  COMMAND_PREFIX: /^[\/!@#]/,
} as const;

export const LIMITS = {
  MAX_MESSAGE_LENGTH: 10000,
  MAX_FILENAME_LENGTH: 255,
  MAX_CHAT_HISTORY_ITEMS: 1000,
  MAX_WAKE_WORDS: 10,
  MAX_RECENT_FILES: 20,
  MAX_SEARCH_RESULTS: 100,
  MIN_WINDOW_WIDTH: 320,
  MIN_WINDOW_HEIGHT: 240,
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_MESSAGES = {
  UNKNOWN_ERROR: 'An unknown error occurred',
  NETWORK_ERROR: 'Network connection error',
  TIMEOUT_ERROR: 'Request timed out',
  PERMISSION_DENIED: 'Permission denied',
  VOICE_UNAVAILABLE: 'Voice transcription unavailable',
  AGENT_BUSY: 'Agent is currently processing another request',
  INVALID_COMMAND: 'Invalid command or parameters',
  CLOUD_DISCONNECTED: 'Cloud service disconnected',
} as const;

export const SUCCESS_MESSAGES = {
  SAVE_SUCCESS: 'Successfully saved',
  UPLOAD_SUCCESS: 'Upload completed',
  CONNECTION_SUCCESS: 'Connected successfully',
  SYNC_SUCCESS: 'Synchronized successfully',
} as const;

export const DEFAULT_CONFIG = {
  theme: 'system',
  language: 'en',
  autoSave: true,
  soundEnabled: true,
  voiceSensitivity: 0.5,
  wakeWords: ['hey juno', 'computer'],
  cloudEnabled: false,
  debugMode: false,
} as const;

// Type helpers
export type EventName = typeof EVENTS[keyof typeof EVENTS];
export type WindowLabel = typeof WINDOW_LABELS[keyof typeof WINDOW_LABELS];
export type ApiEndpoint = typeof API_ENDPOINTS[keyof typeof API_ENDPOINTS];
export type FileExtension = typeof FILE_EXTENSIONS[keyof typeof FILE_EXTENSIONS];
export type PermissionType = typeof PERMISSION_TYPES[keyof typeof PERMISSION_TYPES];
export type ChromeDebugPort = typeof CHROME_DEBUG[keyof typeof CHROME_DEBUG];
export type CommandName = typeof COMMANDS[keyof typeof COMMANDS];
export type DefaultConfig = typeof DEFAULT_CONFIG;
