//! # Tray Menu Module
//!
//! The system tray menu and the menu bar icon for Juno.
//!
//! ## Menu bar icon
//! The icon is a five-bar waveform shipped as a macOS template image (black plus
//! alpha), so the system tints it for the light or dark menu bar and any
//! wallpaper. State lives in the shape, never in color:
//! - Idle: low bars, hotkey ready
//! - Armed: raised bars, always-listening is on and the mic is open
//! - Recording: bars animate while the mic captures speech
//! - Transcribing: three typing dots cycle while audio becomes text
//! - Agent: a shell prompt with a blinking cursor while the agent runs
//! - Error: bars with an exclamation mark, static so it stays readable
//! - Paused: idle bars at 42% opacity, the macOS convention for disabled
//!
//! Frames live in `icons/tray/waveform/` and are generated by
//! `scripts/gen-tray-icons.py`. The tray-icon crate always draws the image
//! 18 pt tall, so every frame is one 36 px PNG (2x).

use crate::constants::{
    errors::{prefixes, templates},
    events,
    menus::tray_menu_ids,
};

// Helper function for error formatting - properly handles template substitution
fn format_error(template: &str, context: &str, error: impl std::fmt::Display) -> String {
    template
        .replacen("{}", context, 1)
        .replacen("{}", &error.to_string(), 1)
}
use crate::state::AppState;
use std::sync::Arc;
use std::time::Duration;
use tauri::{
    image::Image as TauriImage,
    menu::{MenuBuilder, MenuItem, MenuItemBuilder},
    tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder},
    AppHandle, Emitter, Listener, Manager,
};
use tokio::sync::Mutex as TokioMutex;
use tracing::{debug, error, info, warn};

/// Embed one waveform frame from `icons/tray/waveform/`.
macro_rules! tray_frame {
    ($name:literal) => {
        include_bytes!(concat!("../../icons/tray/waveform/", $name, ".png"))
    };
}

const FRAMES_IDLE: &[&[u8]] = &[tray_frame!("idle")];
const FRAMES_ARMED: &[&[u8]] = &[tray_frame!("armed")];
const FRAMES_RECORDING: &[&[u8]] = &[
    tray_frame!("recording-0"),
    tray_frame!("recording-1"),
    tray_frame!("recording-2"),
    tray_frame!("recording-3"),
    tray_frame!("recording-4"),
    tray_frame!("recording-5"),
    tray_frame!("recording-6"),
    tray_frame!("recording-7"),
];
const FRAMES_TRANSCRIBING: &[&[u8]] = &[
    tray_frame!("transcribing-0"),
    tray_frame!("transcribing-1"),
    tray_frame!("transcribing-2"),
    tray_frame!("transcribing-3"),
    tray_frame!("transcribing-4"),
    tray_frame!("transcribing-5"),
];
const FRAMES_AGENT: &[&[u8]] = &[tray_frame!("agent-0"), tray_frame!("agent-1")];
const FRAMES_ERROR: &[&[u8]] = &[tray_frame!("error")];
const FRAMES_PAUSED: &[&[u8]] = &[tray_frame!("paused")];

/// What the menu bar icon is showing. Higher priority states win when several
/// are true at once; see `determine_current_state`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayIconState {
    /// Hotkey ready, nothing happening
    Idle,
    /// Always-listening is on: the mic is open but nothing has been heard yet
    Armed,
    /// The mic is capturing speech
    Recording,
    /// Audio is being turned into text, or the agent is about to start
    Transcribing,
    /// The agent is executing on the Mac
    Agent,
    /// Something needs the person: mic denied, model missing, agent failed
    Error,
    /// Dictation turned off by the person
    Paused,
}

impl TrayIconState {
    /// PNG frames for this state. One frame means static.
    fn frames(self) -> &'static [&'static [u8]] {
        match self {
            TrayIconState::Idle => FRAMES_IDLE,
            TrayIconState::Armed => FRAMES_ARMED,
            TrayIconState::Recording => FRAMES_RECORDING,
            TrayIconState::Transcribing => FRAMES_TRANSCRIBING,
            TrayIconState::Agent => FRAMES_AGENT,
            TrayIconState::Error => FRAMES_ERROR,
            TrayIconState::Paused => FRAMES_PAUSED,
        }
    }

    /// Time between frames for animated states.
    fn frame_interval(self) -> Duration {
        match self {
            TrayIconState::Recording => Duration::from_millis(100),
            TrayIconState::Transcribing => Duration::from_millis(140),
            TrayIconState::Agent => Duration::from_millis(500),
            _ => Duration::from_millis(0),
        }
    }

    /// The state word shown in the tray menu.
    pub fn label(self) -> &'static str {
        match self {
            TrayIconState::Idle => "Ready",
            TrayIconState::Armed => "Listening",
            TrayIconState::Recording => "Recording",
            TrayIconState::Transcribing => "Transcribing",
            TrayIconState::Agent => "Agent running",
            TrayIconState::Error => "Needs attention",
            TrayIconState::Paused => "Paused",
        }
    }

    /// Tooltip for the menu bar icon.
    fn tooltip(self) -> String {
        format!("Juno · {}", self.label())
    }
}

/// Tray icon manager for handling dynamic icon changes
pub struct TrayIconManager {
    tray_icon: Option<TrayIcon<tauri::Wry>>,
    status_item: Option<MenuItem<tauri::Wry>>,
    current_state: TrayIconState,
    /// Bumped on every state change. A running animation loop stops as soon as
    /// it sees a generation other than the one it was started with.
    animation_generation: u64,
}

#[allow(clippy::new_without_default)]
impl TrayIconManager {
    pub fn new() -> Self {
        Self {
            tray_icon: None,
            status_item: None,
            current_state: TrayIconState::Idle,
            animation_generation: 0,
        }
    }

    /// Update the tray icon to reflect the current state
    pub async fn update_icon_state(
        &mut self,
        new_state: TrayIconState,
    ) -> Result<(), Box<dyn std::error::Error>> {
        if self.current_state == new_state {
            debug!("Tray icon state unchanged: {:?}", new_state);
            return Ok(());
        }

        info!(
            "🔄 Updating tray icon state: {:?} -> {:?}",
            self.current_state, new_state
        );

        // Stop whatever animation is running before the first frame goes up.
        self.animation_generation = self.animation_generation.wrapping_add(1);

        let Some(tray_icon) = &self.tray_icon else {
            warn!("No tray icon available to update");
            return Ok(());
        };

        let frames = new_state.frames();
        let first = frames.first().ok_or("tray icon state has no frames")?;
        tray_icon.set_icon(Some(load_tray_icon_from_data(first)?))?;
        tray_icon.set_tooltip(Some(new_state.tooltip()))?;
        if let Some(item) = &self.status_item {
            item.set_text(new_state.label())?;
        }

        self.current_state = new_state;

        if frames.len() > 1 {
            spawn_animation(tray_icon.clone(), new_state, self.animation_generation);
        }

        info!("✅ Tray icon updated successfully");
        Ok(())
    }

    /// Set the tray icon reference
    pub fn set_tray_icon(&mut self, tray_icon: TrayIcon<tauri::Wry>) {
        self.tray_icon = Some(tray_icon);
    }

    /// Set the disabled menu row that shows the state word
    pub fn set_status_item(&mut self, item: MenuItem<tauri::Wry>) {
        self.status_item = Some(item);
    }

    /// Get the current tray icon state
    pub fn current_state(&self) -> &TrayIconState {
        &self.current_state
    }
}

/// Cycle an animated state's frames until the manager moves to another
/// generation. Frame 0 is already showing when this starts.
fn spawn_animation(tray_icon: TrayIcon<tauri::Wry>, state: TrayIconState, generation: u64) {
    tauri::async_runtime::spawn(async move {
        let frames = state.frames();
        let interval = state.frame_interval();
        let mut index = 1usize;
        loop {
            tokio::time::sleep(interval).await;

            let still_current = {
                let manager = get_tray_icon_manager().await;
                let guard = manager.lock().await;
                guard.animation_generation == generation
            };
            if !still_current {
                break;
            }

            let Some(frame) = frames.get(index) else {
                index = 0;
                continue;
            };
            let image = match load_tray_icon_from_data(frame) {
                Ok(image) => image,
                Err(e) => {
                    warn!("Tray animation frame {index} for {state:?} failed to decode: {e}");
                    break;
                }
            };
            if let Err(e) = tray_icon.set_icon(Some(image)) {
                warn!("Tray animation frame {index} for {state:?} failed to apply: {e}");
                break;
            }
            index = (index + 1) % frames.len();
        }
    });
}

/// Global tray icon manager
static TRAY_ICON_MANAGER: TokioMutex<Option<Arc<TokioMutex<TrayIconManager>>>> =
    TokioMutex::const_new(None);

/// Get or create the tray icon manager
async fn get_tray_icon_manager() -> Arc<TokioMutex<TrayIconManager>> {
    let mut manager_guard = TRAY_ICON_MANAGER.lock().await;
    if let Some(manager) = manager_guard.as_ref() {
        manager.clone()
    } else {
        let new_manager = Arc::new(TokioMutex::new(TrayIconManager::new()));
        *manager_guard = Some(new_manager.clone());
        new_manager
    }
}

/// The state the menu bar icon is showing right now
pub async fn current_tray_icon_state() -> TrayIconState {
    let manager = get_tray_icon_manager().await;
    let guard = manager.lock().await;
    *guard.current_state()
}

/// Load tray icon from embedded data
fn load_tray_icon_from_data(
    icon_data: &[u8],
) -> Result<TauriImage<'static>, Box<dyn std::error::Error>> {
    let loaded_image = image::load_from_memory(icon_data)?;
    let width = loaded_image.width();
    let height = loaded_image.height();
    let rgba_image = loaded_image.to_rgba8();
    let bytes = rgba_image.into_raw();
    let img = TauriImage::new_owned(bytes, width, height);
    Ok(img)
}

/// The tray menu plus the disabled first row that shows the state word
pub struct TrayMenu {
    pub menu: tauri::menu::Menu<tauri::Wry>,
    pub status_item: MenuItem<tauri::Wry>,
}

/// Get keyboard shortcuts from app state
fn get_keyboard_shortcuts(
    app: &AppHandle,
) -> Result<crate::state::KeyboardShortcuts, Box<dyn std::error::Error>> {
    let app_state = app.state::<AppState>();
    app_state
        .get_keyboard_shortcuts()
        .map_err(|e| format_error(templates::FAILED_TO_RETRIEVE, "keyboard shortcuts", e).into())
}

/// Create a state-aware tray menu with keyboard shortcuts
pub fn create_state_aware_tray_menu(
    app: &AppHandle,
) -> Result<TrayMenu, Box<dyn std::error::Error>> {
    info!("🍽️ Creating state-aware tray menu...");

    // Get keyboard shortcuts from app state
    let _shortcuts = match get_keyboard_shortcuts(app) {
        Ok(shortcuts) => shortcuts,
        Err(e) => {
            error!(
                "{} {}",
                prefixes::TRAY_MENU,
                format_error(templates::FAILED_TO_RETRIEVE, "keyboard shortcuts", e)
            );
            // Use defaults if we can't get from state
            crate::state::KeyboardShortcuts::default()
        }
    };

    // First row: the state word. Disabled, so it reads as status, not an action.
    let status_item = MenuItemBuilder::new(TrayIconState::Idle.label())
        .id(tray_menu_ids::STATUS)
        .enabled(false)
        .build(app)?;

    // Build menu items with proper accelerators
    let show_hide_item = MenuItemBuilder::new("Show/Hide Chat")
        .id(tray_menu_ids::SHOW_HIDE)
        .build(app)?;

    let new_chat_item = MenuItemBuilder::new("New Chat")
        .id(tray_menu_ids::NEW_CHAT)
        .accelerator("CmdOrCtrl+N")
        .build(app)?;

    let show_hide_floating_item = MenuItemBuilder::new("Show/Hide Floating Bar")
        .id(tray_menu_ids::SHOW_HIDE_FLOATING_BAR)
        .accelerator("CmdOrCtrl+B")
        .build(app)?;

    let dev_tools_item = MenuItemBuilder::new("Developer Tools")
        .id(tray_menu_ids::DEVELOPER_TOOLS)
        .accelerator("CmdOrCtrl+Alt+I")
        .build(app)?;

    // Voice control information items (non-clickable)
    let agent_mode_info = MenuItemBuilder::new("Agent Mode")
        .id("agent_mode_info")
        .accelerator("Alt+D")
        .enabled(false)
        .build(app)?;

    let dictation_mode_info = MenuItemBuilder::new("Dictation Mode")
        .id("dictation_mode_info")
        .enabled(false)
        .build(app)?;

    let stop_task_info = MenuItemBuilder::new("Stop Current Task")
        .id("stop_task_info")
        .accelerator("Escape")
        .enabled(false)
        .build(app)?;

    let settings_item = MenuItemBuilder::new("Settings...")
        .id(tray_menu_ids::SETTINGS)
        .accelerator("CmdOrCtrl+,")
        .build(app)?;

    let quit_item = MenuItemBuilder::new("Quit Juno")
        .id(tray_menu_ids::QUIT)
        .accelerator("CmdOrCtrl+Q")
        .build(app)?;

    // Build the complete tray menu
    let tray_menu = MenuBuilder::new(app)
        .item(&status_item)
        .separator()
        .item(&show_hide_item)
        .item(&new_chat_item)
        .separator()
        .item(&show_hide_floating_item)
        .item(&dev_tools_item)
        .separator()
        .item(&agent_mode_info)
        .item(&dictation_mode_info)
        .item(&stop_task_info)
        .separator()
        .item(&settings_item)
        .separator()
        .item(&quit_item)
        .build()?;

    info!("✅ State-aware tray menu created successfully");
    Ok(TrayMenu {
        menu: tray_menu,
        status_item,
    })
}

/// Create and setup the system tray icon with dynamic state management
pub fn setup_tray_icon(app: &AppHandle) -> Result<(), Box<dyn std::error::Error>> {
    info!("🔧 Setting up system tray icon with dynamic state support...");

    let TrayMenu {
        menu: tray_menu,
        status_item,
    } = create_state_aware_tray_menu(app)?;

    // Load the idle frame. Template mode lets macOS tint it for the menu bar.
    let idle_frame = FRAMES_IDLE.first().ok_or("idle tray icon has no frames")?;
    let default_icon = load_tray_icon_from_data(idle_frame)?;

    let tray_icon = TrayIconBuilder::new()
        .menu(&tray_menu)
        .show_menu_on_left_click(false)
        .icon(default_icon)
        .icon_as_template(true)
        .tooltip(TrayIconState::Idle.tooltip())
        .on_tray_icon_event(|tray, event| {
            handle_tray_icon_event(tray.app_handle(), event);
        })
        .build(app)?;

    // Initialize the tray icon manager
    let app_handle = app.clone();
    tauri::async_runtime::spawn(async move {
        let manager = get_tray_icon_manager().await;
        let mut manager_guard = manager.lock().await;
        manager_guard.set_tray_icon(tray_icon);
        manager_guard.set_status_item(status_item);

        // Start monitoring app state for tray icon updates
        setup_state_monitoring(&app_handle).await;
    });

    info!("✅ System tray icon setup completed with dynamic state support");
    Ok(())
}

/// Setup state monitoring to automatically update tray icon based on app state
async fn setup_state_monitoring(app_handle: &AppHandle) {
    info!("🔍 Setting up tray icon state monitoring...");

    let app_handle_clone = app_handle.clone();

    // Listen for various state change events
    let _ = app_handle.listen(crate::constants::events::agent::ACTIVE, {
        let app_handle = app_handle_clone.clone();
        move |event| {
            let app_handle = app_handle.clone();
            let event = event.clone();
            tauri::async_runtime::spawn(async move {
                if let Ok(is_active) = serde_json::from_str::<bool>(event.payload()) {
                    let new_state = if is_active {
                        TrayIconState::Agent
                    } else {
                        determine_current_state(&app_handle).await
                    };
                    update_tray_icon_state(new_state).await;
                }
            });
        }
    });

    // Listen for dictation state changes (both immediate and confirmed)
    let _ = app_handle.listen(crate::constants::events::dictation::ACTIVE, {
        let app_handle = app_handle_clone.clone();
        move |event| {
            let app_handle = app_handle.clone();
            let event = event.clone();
            tauri::async_runtime::spawn(async move {
                if let Ok(is_active) = serde_json::from_str::<bool>(event.payload()) {
                    let new_state = if is_active {
                        TrayIconState::Recording
                    } else {
                        determine_current_state(&app_handle).await
                    };
                    update_tray_icon_state(new_state).await;
                }
            });
        }
    });

    // Listen for immediate dictation input state changes (when user presses/releases shortcut)
    let _ = app_handle.listen(crate::constants::events::dictation_state::INPUT_CHANGED, {
        let app_handle = app_handle_clone.clone();
        move |event| {
            let app_handle = app_handle.clone();
            tauri::async_runtime::spawn(async move {
                if let Ok(is_pressed) = serde_json::from_str::<bool>(event.payload()) {
                    let new_state = if is_pressed {
                        TrayIconState::Recording
                    } else {
                        determine_current_state(&app_handle).await
                    };
                    update_tray_icon_state(new_state).await;
                }
            });
        }
    });

    // Listen for immediate agent mode starts (when user presses agent shortcut)
    let _ = app_handle.listen(crate::constants::events::dictation::STARTED, {
        move |_event| {
            tauri::async_runtime::spawn(async move {
                // Set to Processing state initially, will change to AgentActive once agent actually starts
                update_tray_icon_state(TrayIconState::Transcribing).await;
            });
        }
    });

    // Listen for dictation completion events (when transcription finishes)
    let _ = app_handle.listen(crate::constants::events::dictation::FINISHED, {
        let app_handle = app_handle_clone.clone();
        move |event| {
            let app_handle = app_handle.clone();
            let event = event.clone();
            tauri::async_runtime::spawn(async move {
                // When dictation finishes, check if it's transitioning to agent mode
                // If there's a query payload, it means agent mode is starting
                if let Ok(payload) = serde_json::from_str::<serde_json::Value>(event.payload()) {
                    if payload.get("query").is_some() {
                        // Dictation finished and agent is about to start
                        update_tray_icon_state(TrayIconState::Transcribing).await;
                    } else {
                        // Just dictation finishing without agent mode
                        let new_state = determine_current_state(&app_handle).await;
                        update_tray_icon_state(new_state).await;
                    }
                } else {
                    // Fallback - just determine current state
                    let new_state = determine_current_state(&app_handle).await;
                    update_tray_icon_state(new_state).await;
                }
            });
        }
    });

    // Listen for agent-query-ready events (when agent mode voice transcription finishes)
    let _ = app_handle.listen(crate::constants::events::agent::QUERY_READY, {
        move |_event| {
            tauri::async_runtime::spawn(async move {
                // When agent voice transcription finishes, agent processing is about to start
                update_tray_icon_state(TrayIconState::Transcribing).await;
            });
        }
    });

    let _ = app_handle.listen(crate::constants::events::always_listening::MODE_CHANGED, {
        let app_handle = app_handle_clone.clone();
        move |event| {
            let app_handle = app_handle.clone();
            let event = event.clone();
            tauri::async_runtime::spawn(async move {
                if let Ok(is_active) = serde_json::from_str::<bool>(event.payload()) {
                    if is_active {
                        update_tray_icon_state(TrayIconState::Armed).await;
                    } else {
                        let new_state = determine_current_state(&app_handle).await;
                        update_tray_icon_state(new_state).await;
                    }
                }
            });
        }
    });

    // Listen for floating bar state changes to detect processing states
    let _ = app_handle.listen(crate::constants::events::ui::BAR_STATE_CHANGED, {
        move |event| {
            tauri::async_runtime::spawn(async move {
                let event = event.clone();
                if let Ok(payload) = serde_json::from_str::<serde_json::Value>(event.payload()) {
                    if let Some(state) = payload.get("barState").and_then(|s| s.as_str()) {
                        let icon_state = match state {
                            "loading" | "transcribing" | "dictation_processing" => {
                                Some(TrayIconState::Transcribing)
                            }
                            "agent_thinking" => Some(TrayIconState::Agent),
                            "error" => Some(TrayIconState::Error),
                            _ => None,
                        };

                        if let Some(state) = icon_state {
                            update_tray_icon_state(state).await;
                        }
                    }
                }
            });
        }
    });

    // Listen for voice system errors
    let _ = app_handle.listen(crate::constants::events::dictation::ERROR, {
        let app_handle = app_handle_clone.clone();
        move |_event| {
            let app_handle = app_handle.clone();
            tauri::async_runtime::spawn(async move {
                update_tray_icon_state(TrayIconState::Error).await;

                // After a delay, reset to current state
                tokio::time::sleep(tokio::time::Duration::from_secs(3)).await;
                let new_state = determine_current_state(&app_handle).await;
                update_tray_icon_state(new_state).await;
            });
        }
    });

    // Listen for voice transcription errors
    let _ = app_handle.listen(crate::constants::events::voice_transcription::ERROR, {
        let app_handle = app_handle_clone.clone();
        move |_event| {
            let app_handle = app_handle.clone();
            tauri::async_runtime::spawn(async move {
                update_tray_icon_state(TrayIconState::Error).await;

                // After a delay, reset to current state
                tokio::time::sleep(tokio::time::Duration::from_secs(3)).await;
                let new_state = determine_current_state(&app_handle).await;
                update_tray_icon_state(new_state).await;
            });
        }
    });

    info!("✅ Tray icon state monitoring setup completed");
}

/// Determine the current tray icon state based on app state
async fn determine_current_state(app_handle: &AppHandle) -> TrayIconState {
    let app_state = app_handle.state::<AppState>();

    // Check states in order of priority
    let is_agent = app_state.is_agent_executing();
    let is_dictation = app_state.is_dictation_active();
    let is_always_listening = app_state.get_always_listening_active().unwrap_or(false);

    info!(
        "🔍 Tray icon state check - Agent: {}, Dictation: {}, Always Listening: {}",
        is_agent, is_dictation, is_always_listening
    );

    if is_agent {
        return TrayIconState::Agent;
    }

    if is_dictation {
        return TrayIconState::Recording;
    }

    // Check always listening state
    if is_always_listening {
        info!("Always listening is active, showing the armed icon");
        return TrayIconState::Armed;
    }

    info!("No active states, showing the idle icon");
    TrayIconState::Idle
}

/// Update the tray icon state
pub async fn update_tray_icon_state(new_state: TrayIconState) {
    let manager = get_tray_icon_manager().await;
    let mut manager_guard = manager.lock().await;

    if let Err(e) = manager_guard.update_icon_state(new_state).await {
        error!(
            "{} {}",
            prefixes::TRAY_MENU,
            format_error(templates::FAILED_TO_EMIT, "tray state updated", e)
        );
    }
}

/// Public function to manually update tray icon state
pub async fn set_tray_icon_state(state: TrayIconState) {
    update_tray_icon_state(state).await;
}

/// Convenience functions for common state changes
///
/// Set tray icon to indicate the agent is running
pub async fn set_agent() {
    set_tray_icon_state(TrayIconState::Agent).await;
}

/// Set tray icon to indicate the mic is capturing speech
pub async fn set_recording() {
    set_tray_icon_state(TrayIconState::Recording).await;
}

/// Set tray icon to indicate always-listening is on
pub async fn set_armed() {
    set_tray_icon_state(TrayIconState::Armed).await;
}

/// Set tray icon to indicate audio is becoming text
pub async fn set_transcribing() {
    set_tray_icon_state(TrayIconState::Transcribing).await;
}

/// Set tray icon to indicate something needs the person
pub async fn set_error() {
    set_tray_icon_state(TrayIconState::Error).await;
}

/// Set tray icon to indicate dictation is turned off
pub async fn set_paused() {
    set_tray_icon_state(TrayIconState::Paused).await;
}

/// Reset tray icon to idle
pub async fn set_idle() {
    set_tray_icon_state(TrayIconState::Idle).await;
}

/// Handle tray menu events
pub fn handle_tray_menu_events(app_handle: AppHandle, event_id: &str) {
    // Only handle events that are actually tray menu events
    // Ignore app menu and edit menu events that are handled by the global menu handler
    if !crate::menu::is_tray_menu_event(event_id) {
        // Silently ignore non-tray events - they're handled by the global menu handler
        return;
    }

    match event_id {
        tray_menu_ids::SHOW_HIDE => {
            info!("[TrayMenu] Show/Hide Chat menu item clicked");
            // The floating bar is the app's surface now; make sure it is visible,
            // then toggle its chat pane so this reopens a dismissed conversation
            // (or hides it again).
            let label = crate::constants::ui::window_labels::FLOATING_BAR;
            if let Some(window) = app_handle.get_webview_window(label) {
                if !window.is_visible().unwrap_or(false) {
                    let _ = window.show();
                }
            }
            if let Err(e) = app_handle.emit(events::bar::TOGGLE_PANE, ()) {
                error!(
                    "{} {}",
                    prefixes::TRAY_MENU,
                    format_error(templates::FAILED_TO_EMIT, "toggle chat pane", e)
                );
            }
        }
        tray_menu_ids::NEW_CHAT => {
            info!("[TrayMenu] New Chat menu item clicked");
            if let Err(e) = app_handle.emit(events::menu::NEW_CHAT_REQUESTED, ()) {
                error!(
                    "{} {}",
                    prefixes::TRAY_MENU,
                    format_error(templates::FAILED_TO_EMIT, "new chat", e)
                );
            }
        }
        tray_menu_ids::SHOW_HIDE_FLOATING_BAR => {
            info!("[TrayMenu] Show/Hide Floating Bar menu item clicked");
            if let Err(e) = app_handle.emit(events::menu::TOGGLE_FLOATING_BAR_REQUESTED, ()) {
                error!(
                    "{} {}",
                    prefixes::TRAY_MENU,
                    format_error(templates::FAILED_TO_EMIT, "toggle floating bar", e)
                );
            }
        }
        tray_menu_ids::DEVELOPER_TOOLS => {
            info!("[TrayMenu] Developer Tools menu item clicked");
            if let Err(e) = app_handle.emit(events::menu::DEVTOOLS_REQUESTED, ()) {
                error!(
                    "{} {}",
                    prefixes::TRAY_MENU,
                    format_error(templates::FAILED_TO_EMIT, "devtools", e)
                );
            }
        }
        tray_menu_ids::SETTINGS => {
            info!("[TrayMenu] Settings menu item clicked");
            // Call open_settings_window directly instead of emitting event
            let app_handle_clone = app_handle.clone();
            tauri::async_runtime::spawn(async move {
                if let Err(e) =
                    crate::window_management::open_settings_window(app_handle_clone).await
                {
                    error!(
                        "{} {}",
                        prefixes::TRAY_MENU,
                        format_error(templates::FAILED_TO_PROCESS, "settings window open", e)
                    );
                }
            });
        }
        tray_menu_ids::QUIT => {
            info!("[TrayMenu] Quit menu item clicked");
            app_handle.exit(0);
        }
        _ => {
            // This should never happen since we filter for tray events above
            warn!("[TrayMenu] Unexpected tray menu event: {}", event_id);
        }
    }
}

/// Handle TrayIconEvents like clicks on the icon itself
pub fn handle_tray_icon_event(app_handle: &AppHandle, event: tauri::tray::TrayIconEvent) {
    match event {
        tauri::tray::TrayIconEvent::Click {
            button: MouseButton::Left,
            button_state: MouseButtonState::Up,
            ..
        } => {
            info!("[TrayIcon] Left click detected on tray icon");
            // Show/focus the main window when tray icon is left-clicked
            if let Some(window) = app_handle.get_webview_window("main") {
                let is_visible = window.is_visible().unwrap_or(false);
                let is_focused = window.is_focused().unwrap_or(false);
                if is_visible && is_focused {
                    // Window is visible and focused — hide it (toggle behavior)
                    let _ = window.hide();
                } else {
                    // Window is hidden or not focused — show and focus it
                    let _ = window.show();
                    let _ = window.unminimize();
                    let _ = window.set_focus();
                }
            }
        }
        tauri::tray::TrayIconEvent::Click {
            button: MouseButton::Right,
            button_state: MouseButtonState::Up,
            ..
        } => {
            info!("[TrayIcon] Right click detected on tray icon");
            // Right click behavior is handled by menu system
        }
        _ => {
            // Handle other tray icon events if needed
        }
    }
}

/// Enhanced tray menu refresh function
pub fn refresh_tray_menu(app_handle: &AppHandle) {
    info!("[TrayMenu] Refreshing tray menu...");

    match create_state_aware_tray_menu(app_handle) {
        Ok(_new_menu) => {
            info!("[TrayMenu] Successfully refreshed tray menu");
            // Note: Tauri v2 will handle menu updates automatically through the state
        }
        Err(e) => {
            error!(
                "{} {}",
                prefixes::TRAY_MENU,
                format_error(templates::FAILED_TO_LOAD, "tray menu refresh", e)
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const ALL_STATES: [TrayIconState; 7] = [
        TrayIconState::Idle,
        TrayIconState::Armed,
        TrayIconState::Recording,
        TrayIconState::Transcribing,
        TrayIconState::Agent,
        TrayIconState::Error,
        TrayIconState::Paused,
    ];

    #[test]
    fn every_frame_is_a_36px_template_image() {
        // Template images are black plus alpha. Any color would be flattened by
        // macOS, so a colored pixel means the generator drifted.
        for state in ALL_STATES {
            for (index, frame) in state.frames().iter().enumerate() {
                let image = image::load_from_memory(frame)
                    .unwrap_or_else(|e| panic!("{state:?} frame {index} failed to decode: {e}"));
                assert_eq!(
                    (image.width(), image.height()),
                    (36, 36),
                    "{state:?} frame {index}"
                );
                let rgba = image.to_rgba8();
                let colored = rgba
                    .pixels()
                    .filter(|p| p[3] > 0 && (p[0] > 0 || p[1] > 0 || p[2] > 0))
                    .count();
                assert_eq!(colored, 0, "{state:?} frame {index} has colored pixels");
                let visible = rgba.pixels().filter(|p| p[3] > 0).count();
                assert!(visible > 0, "{state:?} frame {index} is blank");
            }
        }
    }

    #[test]
    fn animated_states_have_frames_and_an_interval() {
        for state in ALL_STATES {
            let animated = state.frames().len() > 1;
            assert_eq!(
                animated,
                !state.frame_interval().is_zero(),
                "{state:?}: frame count and interval disagree"
            );
        }
        assert!(TrayIconState::Recording.frames().len() > 1);
        assert!(TrayIconState::Transcribing.frames().len() > 1);
        assert!(TrayIconState::Agent.frames().len() > 1);
        assert_eq!(TrayIconState::Error.frames().len(), 1, "error stays static");
    }

    #[test]
    fn every_state_has_a_label_and_tooltip() {
        for state in ALL_STATES {
            assert!(!state.label().is_empty(), "{state:?}");
            assert!(state.tooltip().starts_with("Juno"), "{state:?}");
        }
        assert_eq!(TrayIconState::Idle.label(), "Ready");
        assert_eq!(TrayIconState::Error.label(), "Needs attention");
    }

    #[test]
    fn tray_menu_constants_exist() {
        assert!(!tray_menu_ids::STATUS.is_empty());
        assert!(!tray_menu_ids::QUIT.is_empty());
        assert!(!tray_menu_ids::SETTINGS.is_empty());
        assert!(!tray_menu_ids::SHOW_FLOATING_BAR.is_empty());
        assert!(!tray_menu_ids::HIDE_FLOATING_BAR.is_empty());
        assert!(!tray_menu_ids::SHOW_MAIN_WINDOW.is_empty());
        assert!(!tray_menu_ids::HIDE_MAIN_WINDOW.is_empty());
        assert!(!tray_menu_ids::NEW_CHAT.is_empty());
        assert!(!tray_menu_ids::SHOW_DEVTOOLS.is_empty());
        assert!(!tray_menu_ids::TOGGLE_FLOATING_BAR.is_empty());
    }
}
