//! Deleting is recoverable: Juno's shell deletes to the macOS Trash.
//!
//! Lacy's rule: "it should never rm -rf, instead it should move stuff to the
//! trash." The reason that rule is worth building rather than asking about is
//! in `docs/plans/permissions-by-consequence.md`: the answer to a destructive
//! action is usually to make it undoable, not to interrupt someone about it. A
//! delete that lands in the Trash needs no dialog, so a whole category of
//! question disappears instead of getting better copy.
//!
//! ## How, and why not the obvious way
//!
//! The obvious way is to inspect the command and rewrite `rm` into `trash`.
//! That is string surgery on shell syntax, and it is wrong for the same reason
//! the risk classifier's substring tests are wrong: globs, quoting, variables,
//! `xargs`, chaining and `find -exec` all mean the paths an `rm` will actually
//! touch are not in the command text. You cannot read them out of it.
//!
//! So Juno does not rewrite the command. It changes what `rm` is. The shell
//! session writes this script to `<session>/bin/rm` and prepends that
//! directory to `PATH`, so bash resolves `rm` to it. Bash has already done all
//! the parsing by then: the shim's `"$@"` holds real, expanded, unquoted paths.
//! There is nothing left to guess.
//!
//! ## What it does when the Trash cannot help
//!
//! It refuses, and it does not delete. A path on a network volume, a read-only
//! mount, or a filesystem with nowhere to put a Trash cannot be made
//! recoverable, so the shim exits non-zero and says so. The model sees a
//! failure with a reason and can ask the person, which is the right outcome:
//! this is exactly the case the policy says must ask rather than proceed.
//! Falling back to a real delete would turn "safe by construction" into a lie.
//!
//! ## What it does not cover
//!
//! `/bin/rm` by absolute path, and anything that unlinks through a syscall
//! rather than through `rm`. That is why
//! [`crate::commands::shell::refuse_forbidden_command`] keeps refusing the
//! catastrophic forms: the shim makes ordinary deleting recoverable, and the
//! refusal gate holds the floor under it. Two layers, two jobs.

/// macOS ships this from Sonoma on. It moves a path to the correct Trash for
/// whatever volume the path lives on, which is the part that is tedious and
/// easy to get wrong by hand.
pub const TRASH_BINARY: &str = "/usr/bin/trash";

/// The directory name, inside the shell session directory, that holds the
/// shims and goes on the front of `PATH`.
pub const SHIM_DIR_NAME: &str = "bin";

/// The `rm` Juno's shell session runs.
///
/// Pure: builds the script text and nothing else, so it can be read and tested
/// without running it.
///
/// Behaviour, matched to `rm` where it matters so build scripts keep working:
///
/// - `-f` makes a missing target silent and successful, as `rm -f` does.
/// - Flags are parsed only until `--`, so a file genuinely named `-f` works.
/// - Every target is attempted; one failure does not skip the rest, and the
///   exit status is non-zero if any failed.
/// - A target that cannot go to the Trash is **not deleted**.
pub fn rm_shim_script() -> String {
    format!(
        r#"#!/bin/bash
# Juno's rm. Deleting here is recoverable: files go to the macOS Trash.
# Generated by src-tauri/src/trash.rs. Do not edit; it is rewritten per session.
set -u

TRASH_BIN={trash_bin}

force=0
after_dashdash=0
targets=()

for arg in "$@"; do
  if [ "$after_dashdash" -eq 1 ]; then
    targets+=("$arg")
    continue
  fi
  case "$arg" in
    --)
      after_dashdash=1
      ;;
    --force)
      force=1
      ;;
    --*)
      # --recursive, --dir, --verbose, --interactive and friends: the Trash is
      # recursive and this shim is never interactive, so they are no-ops.
      ;;
    -?*)
      case "$arg" in *f*) force=1 ;; esac
      ;;
    *)
      targets+=("$arg")
      ;;
  esac
done

if [ ! -x "$TRASH_BIN" ]; then
  echo "rm: cannot delete safely: $TRASH_BIN is missing, so this delete could not be undone. Nothing was deleted. Ask the person before deleting without the Trash." >&2
  exit 1
fi

if [ ${{#targets[@]}} -eq 0 ]; then
  if [ "$force" -eq 1 ]; then
    exit 0
  fi
  echo "rm: missing operand" >&2
  exit 1
fi

status=0
for target in "${{targets[@]}}"; do
  if [ ! -e "$target" ] && [ ! -L "$target" ]; then
    if [ "$force" -eq 1 ]; then
      continue
    fi
    echo "rm: $target: No such file or directory" >&2
    status=1
    continue
  fi
  if ! "$TRASH_BIN" "$target" >/dev/null 2>&1; then
    echo "rm: $target: the Trash cannot take this, so deleting it would be permanent. Nothing was deleted. Ask the person first." >&2
    status=1
  fi
done

exit $status
"#,
        trash_bin = TRASH_BINARY
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_shim_deletes_through_the_trash_and_never_through_rm() {
        let script = rm_shim_script();
        assert!(
            script.contains(TRASH_BINARY),
            "the shim has to call the Trash tool or it is not a shim"
        );
        // The one line that would undo the whole point of this file.
        for escape_hatch in ["/bin/rm", "unlink ", "rmdir ", "command rm"] {
            assert!(
                !script.contains(escape_hatch),
                "the shim must never fall back to a real delete, found {escape_hatch:?}"
            );
        }
    }

    #[test]
    fn a_target_the_trash_refuses_is_reported_and_kept() {
        let script = rm_shim_script();
        assert!(
            script.contains("Nothing was deleted"),
            "a refusal has to say the file is still there"
        );
        assert!(
            script.contains("Ask the person first"),
            "the model needs to be told the next step is asking, not retrying"
        );
        // Non-zero on failure, or the model reads a refusal as a success.
        assert!(script.contains("status=1"));
        assert!(script.contains("exit $status"));
    }

    #[test]
    fn force_on_a_missing_target_stays_silent_and_successful() {
        // `rm -f nonexistent` exits 0 everywhere, and build scripts rely on it.
        let script = rm_shim_script();
        assert!(script.contains("force=1"));
        assert!(script.contains("exit 0"));
    }

    #[test]
    fn flag_parsing_stops_at_a_double_dash() {
        let script = rm_shim_script();
        assert!(
            script.contains("after_dashdash"),
            "a file named -f has to be deletable"
        );
    }

    #[test]
    fn the_script_is_a_bash_script_because_it_needs_arrays() {
        let script = rm_shim_script();
        assert!(script.starts_with("#!/bin/bash"));
        assert!(script.contains("targets=()"));
        // No unexpanded format placeholders left behind.
        assert!(!script.contains("{trash_bin}"));
    }
}
